//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public int Id { get; set; }
        public bool Approved { get; set; }
    
        public virtual Worker Worker { get; set; }
        public virtual Decision Decision { get; set; }
    }
}
