//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decision
    {
        public int Id { get; set; }
        public string Explanation { get; set; }
        public bool Empolyed { get; set; }
        public bool Resigned { get; set; }
        public bool Accepted { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual Approval Approval { get; set; }
    }
}
