//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Id { get; set; }
        public System.DateTime FromYear { get; set; }
        public string SchoolName { get; set; }
        public System.DateTime ToYear { get; set; }
        public string Name { get; set; }
    
        public virtual Recruited Recruited { get; set; }
    }
}
