//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessionalExperience
    {
        public int Id { get; set; }
        public string Job { get; set; }
        public string Company { get; set; }
        public System.DateTime From { get; set; }
        public System.DateTime To { get; set; }
        public int RecruitedId { get; set; }
    
        public virtual Recruited Recruited { get; set; }
    }
}
