//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class StageGrade
    {
        public int Id { get; set; }
        public Nullable<byte> Grade { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual Application Applications { get; set; }
    }
}
