//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_v1
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Recruited))]
    [KnownType(typeof(Jobs))]
    [KnownType(typeof(StageGrades))]
    [KnownType(typeof(Workers))]
    
    public partial class Applications
    {
        public Applications()
        {
            this.StageGrades = new HashSet<StageGrades>();
        }
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string Explenation { get; set; }
    	[DataMember]
        public byte YearsOfExpirience { get; set; }
    	[DataMember]
        public bool Employed { get; set; }
    	[DataMember]
        public bool Resigned { get; set; }
    	[DataMember]
        public bool Approved { get; set; }
    
    	[DataMember]
        public virtual Recruited Recruited { get; set; }
    	[DataMember]
        public virtual Jobs Jobs { get; set; }
    	[DataMember]
        public virtual ICollection<StageGrades> StageGrades { get; set; }
    	[DataMember]
        public virtual Workers Workers { get; set; }
    	[DataMember]
        public virtual Workers Workers1 { get; set; }
    }
}
