//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_v1
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Recruited))]
    [KnownType(typeof(Skills))]
    
    public partial class Documents
    {
        public Documents()
        {
            this.Skills = new HashSet<Skills>();
        }
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public byte[] File { get; set; }
    
    	[DataMember]
        public virtual Recruited Recruited { get; set; }
    	[DataMember]
        public virtual ICollection<Skills> Skills { get; set; }
    }
}
