//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_v1
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Requires))]
    [KnownType(typeof(Applications))]
    [KnownType(typeof(Stage))]
    
    public partial class Jobs
    {
        public Jobs()
        {
            this.Requires = new HashSet<Requires>();
            this.Applications = new HashSet<Applications>();
            this.Stage = new HashSet<Stage>();
        }
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string Name { get; set; }
    
    	[DataMember]
        public virtual ICollection<Requires> Requires { get; set; }
    	[DataMember]
        public virtual ICollection<Applications> Applications { get; set; }
    	[DataMember]
        public virtual ICollection<Stage> Stage { get; set; }
    }
}
