//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_v1
{
    using System;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
    	public ModelContainer()
            : this(false) { }
    
        public ModelContainer(bool proxyCreationEnabled)
            : base("name=ModelContainer")
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    	
        public ModelContainer(string connectionString)
          : this(connectionString, false) { }
    	  
        public ModelContainer(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    	
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Recruited> RecruitedSet { get; set; }
        public virtual DbSet<Skills> SkillsSet { get; set; }
        public virtual DbSet<Documents> DocumentsSet { get; set; }
        public virtual DbSet<Posesses> PosessesSet { get; set; }
        public virtual DbSet<Jobs> JobsSet { get; set; }
        public virtual DbSet<Requires> RequiresSet { get; set; }
        public virtual DbSet<Applications> ApplicationsSet { get; set; }
        public virtual DbSet<Stage> StageSet { get; set; }
        public virtual DbSet<StageGrades> StageGradesSet { get; set; }
        public virtual DbSet<Workers> WorkersSet { get; set; }
        public virtual DbSet<Roles> RolesSet { get; set; }
    }
}
