//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_v1
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Posesses))]
    [KnownType(typeof(Documents))]
    [KnownType(typeof(Applications))]
    
    public partial class Recruited
    {
        public Recruited()
        {
            this.Posesses = new HashSet<Posesses>();
            this.Documents = new HashSet<Documents>();
            this.Applications = new HashSet<Applications>();
        }
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string DateOfBirth { get; set; }
    	[DataMember]
        public string Education { get; set; }
    	[DataMember]
        public string email { get; set; }
    	[DataMember]
        public string PhoneNumber { get; set; }
    	[DataMember]
        public string Nationality { get; set; }
    	[DataMember]
        public string FathersName { get; set; }
    
    	[DataMember]
        public virtual ICollection<Posesses> Posesses { get; set; }
    	[DataMember]
        public virtual ICollection<Documents> Documents { get; set; }
    	[DataMember]
        public virtual ICollection<Applications> Applications { get; set; }
    }
}
