//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_v1
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Skills))]
    [KnownType(typeof(Jobs))]
    
    public partial class Requires
    {
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public double Weight { get; set; }
    
    	[DataMember]
        public virtual Skills Skills { get; set; }
    	[DataMember]
        public virtual Jobs Jobs { get; set; }
    }
}
