//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_v1
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Posesses))]
    [KnownType(typeof(Documents))]
    [KnownType(typeof(Requires))]
    
    public partial class Skills
    {
        public Skills()
        {
            this.Posesses = new HashSet<Posesses>();
            this.Documents = new HashSet<Documents>();
            this.Requires = new HashSet<Requires>();
        }
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string Name { get; set; }
    
    	[DataMember]
        public virtual ICollection<Posesses> Posesses { get; set; }
    	[DataMember]
        public virtual ICollection<Documents> Documents { get; set; }
    	[DataMember]
        public virtual ICollection<Requires> Requires { get; set; }
    }
}
