//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_v1
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(StageGrades))]
    [KnownType(typeof(Jobs))]
    [KnownType(typeof(Workers))]
    
    public partial class Stage
    {
        public Stage()
        {
            this.StageGrades = new HashSet<StageGrades>();
            this.Jobs = new HashSet<Jobs>();
            this.Workers = new HashSet<Workers>();
        }
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string Name { get; set; }
    
    	[DataMember]
        public virtual ICollection<StageGrades> StageGrades { get; set; }
    	[DataMember]
        public virtual ICollection<Jobs> Jobs { get; set; }
    	[DataMember]
        public virtual ICollection<Workers> Workers { get; set; }
    }
}
