//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD2_v1
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Stage))]
    [KnownType(typeof(Applications))]
    
    public partial class StageGrades
    {
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public Nullable<byte> Grade { get; set; }
    
    	[DataMember]
        public virtual Stage Stage { get; set; }
    	[DataMember]
        public virtual Applications Applications { get; set; }
    }
}
